### ISSUE TITLE
オリンピックの英語表現

### ISSUE THREAD

**Issue by chikuwa111** [chikuwa111/ruby_study_final_work#9]
the Olympicsでひとつの大会を指す場合が多いみたい。
Olympicは基本的に形容詞で使う。（例: Olympic games）

参考
http://dictionary.cambridge.org/dictionary/english/olympic?q=Olympic
http://www.dictionary.com/browse/olympic

**Comment by Kite0301** [comment]
```rb
olympics_data = [
  {year: 1896, city: "アテネ", country: "ギリシャ", area: "ヨーロッパ"},
  {year: 1900, city: "パリ", country: "フランス", area: "ヨーロッパ"},
]
```

みたいな感じだと、eachの時に変数名に困る。

**Comment by chikuwa111** [comment]
結局現状のままolympicsが複数でolympicが単数のように振る舞うようにする
